/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.common.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.macro.mall.common.api.IErrorCode;
import com.macro.mall.common.exception.ApiException;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ApiException_SSTest extends ApiException_SSTest_scaffolding {
// allCoveredLines:[13, 14, 15, 18, 19, 22, 23, 26, 27, 30]

  @Test(timeout = 4000)
  public void test_getErrorCode_0()  throws Throwable  {
      //caseID:b83662b3169f75a97796c669f788bd2c
      //CoveredLines: [22, 23, 30]
      //Assert: assertNull(method_result);
      
      //mock throwable0
      Throwable throwable0 = mock(Throwable.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      ApiException apiException0 = new ApiException(throwable0);
      
      //Call method: getErrorCode
      IErrorCode iErrorCode0 = apiException0.getErrorCode();
      
      //Test Result Assert
      assertNull(iErrorCode0);
  }

  @Test(timeout = 4000)
  public void test_getErrorCode_1()  throws Throwable  {
      //caseID:e7c1d1f212ab6add2826c40b79c3b56b
      //CoveredLines: [26, 27, 30]
      //Assert: assertNull(method_result);
      
      //mock throwable0
      Throwable throwable0 = mock(Throwable.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      ApiException apiException0 = new ApiException("", throwable0);
      
      //Call method: getErrorCode
      IErrorCode iErrorCode0 = apiException0.getErrorCode();
      
      //Test Result Assert
      assertNull(iErrorCode0);
  }

  @Test(timeout = 4000)
  public void test_getErrorCode_2()  throws Throwable  {
      //caseID:c0cfed03a8f6e7f213d5b8ca9e5e1d1a
      //CoveredLines: [18, 19, 30]
      //Assert: assertNull(method_result);
      
      ApiException apiException0 = new ApiException("42");
      
      //Call method: getErrorCode
      IErrorCode iErrorCode0 = apiException0.getErrorCode();
      
      //Test Result Assert
      assertNull(iErrorCode0);
  }

  @Test(timeout = 4000)
  public void test_getErrorCode_3()  throws Throwable  {
      //caseID:3d74cedc5456a4749c0ef0bb1ebe6e3e
      //CoveredLines: [13, 14, 15, 30]
      //Assert: assertSame(method_result, iErrorCode0);
      
      //mock iErrorCode0
      IErrorCode iErrorCode0 = mock(IErrorCode.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      ApiException apiException0 = new ApiException(iErrorCode0);
      
      //Call method: getErrorCode
      IErrorCode iErrorCode1 = apiException0.getErrorCode();
      
      //Test Result Assert
      assertSame(iErrorCode1, iErrorCode0);
  }
}
